import Head from "next/head";
import { Inter } from "next/font/google";
import { useQuery } from "@apollo/client";
import { REALTIMEPRICE } from "@/graphql/queries";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data, loading, error } = useQuery(REALTIMEPRICE, {
    variables: { currency: "NGN" },
    fetchPolicy: "cache-and-network",
  });
  console.log(loading);
  console.log(error);
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
